/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/Views/**/*.php",
    "./app/Cells/**/*.php",
    "./public/assets/**/*.html",
  ],
  theme: {
    extend: {
      "colors": {
        "primary": "#006c4a",
        "on-primary": "#ffffff",
        "primary-container": "#89f8c6",
        "on-primary-container": "#002114",
        "primary-fixed": "#89f8c6",
        "on-primary-fixed": "#002114",
        "primary-fixed-dim": "#6cebc0",
        "on-primary-fixed-variant": "#005237",
        "secondary": "#4d6357",
        "on-secondary": "#ffffff",
        "secondary-container": "#cfe9d9",
        "on-secondary-container": "#092016",
        "secondary-fixed": "#cfe9d9",
        "on-secondary-fixed": "#092016",
        "secondary-fixed-dim": "#b3ccbe",
        "on-secondary-fixed-variant": "#354b40",
        "tertiary": "#3d6373",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c1e8fb",
        "on-tertiary-container": "#001f29",
        "tertiary-fixed": "#c1e8fb",
        "on-tertiary-fixed": "#001f29",
        "tertiary-fixed-dim": "#a5ccdf",
        "on-tertiary-fixed-variant": "#254b5a",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",
        "background": "#fbfdf9",
        "on-background": "#191c1a",
        "surface": "#fbfdf9",
        "on-surface": "#191c1a",
        "surface-variant": "#dce5dd",
        "on-surface-variant": "#404943",
        "outline": "#707973",
        "outline-variant": "#c0c9c1",
        "surface-dim": "#d9dbd8",
        "surface-bright": "#fbfdf9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f8f4",
        "surface-container": "#f0f3ef",
        "surface-container-high": "#eaedea",
        "surface-container-highest": "#e4e8e4",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#f0f1ee",
        "inverse-primary": "#6cebc0",
        "surface-tint": "#006c4a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-lg": "24px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "section-gap": "64px",
        "gutter": "24px",
        "stack-md": "16px",
        "sidebar_width": "280px",
        "margin_desktop": "32px",
        "container_max_width": "1280px",
        "base": "24px"
      },
      "fontFamily": {
        "headline-md": ["Work Sans"],
        "body-lg": ["Inter"],
        "headline-xl-mobile": ["Work Sans"],
        "headline-lg": ["Work Sans"],
        "headline-xl": ["Work Sans"],
        "caption": ["Inter"],
        "display-lg": ["Work Sans"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Work Sans"],
        "data-table": ["Inter"],
        "label-sm": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.7", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg": ["30px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "data-table": ["14px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
